### ISSUE TITLE
failed to find module or file: yp

### ISSUE THREAD

**Issue by hyer** [guludo/yape#1]
I have installed the version of 0.2.1 with pip, and create a script hello.py with:

```python
import yape as yp

@yp.nodeop
def hello(who="world"):
    print(f"Hello, {who}!")

```
I run in cmd with `yape`, but got error:

```bash
Traceback (most recent call last):
  File "/usr/local/bin/yape", line 8, in <module>
    sys.exit(run())
  File "/usr/local/lib/python3.8/site-packages/yape/__main__.py", line 4, in run
    exit(cli.run())
  File "/usr/local/lib/python3.8/site-packages/yape/climodule.py", line 32, in run
    self.__load_yp()
  File "/usr/local/lib/python3.8/site-packages/yape/climodule.py", line 80, in __load_yp
    raise RuntimeError(f'failed to find module or file: {name}')
RuntimeError: failed to find module or file: yp
```

Env:
MacOS, python3.8

**Comment by guludo** [comment]
Hello @hyer!

Your file should be named `yp.py` instead of `hello.py`. If you prefer to use the latter, you can run `yape --yp hello` tell it to use the alternate module name.

Also note that your example will also fail because you are using `@yp.nodeop`. I think you meant to use `@yp.node` instead.

Btw, I just made a new release (0.3.0).
